version: "3.8"

services:
  nginx:
    image: ghcr.io/alexbidenko1998/chinchillas-show/nginx:latest
    expose:
      - 80
    ports:
      - "8888:80"
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - application
      - server

  application:
    image: ghcr.io/alexbidenko1998/chinchillas-show/application:latest
    expose:
      - 3333
    ports:
      - "3333:3333"
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - application
      - server

networks:
  application:
  server:
    external:
      name: server
