version: '3.8'

services:
  application:
    restart: unless-stopped
    build: .
    expose:
      - 3333
  nginx:
    restart: unless-stopped
    build: ./.nginx
    container_name: chinhillas_show
    expose:
      - 80
    depends_on:
      - application

networks:
  server:
    external: true
