version: '3.8'

services:
  application:
    restart: unless-stopped
    build: .
    expose:
      - 3333
    networks:
      - app_network
    ports:
      - "3333:3333"
  nginx:
    restart: unless-stopped
    build: ./.nginx
    container_name: chinchillas_show
    expose:
      - 80
    ports:
      - "8888:80"
    depends_on:
      - application
    networks:
      - app_network
      - server

networks:
  app_network:
    driver: bridge
  server:
    external: true
