version: '3'

services:
  nuxt:
    restart: always
    build: .
    ports:
      - 3333:3333
#  nginx:
#    restart: always
#    build: ./.nginx
#    ports:
#      - 0.0.0.0:80:80
#      - 0.0.0.0:433:433
#    depends_on:
#      - nuxt
