name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish Application
        run: |
          docker build . --tag ghcr.io/alexbidenko1998/chinchillas-show/application:latest
          docker push ghcr.io/alexbidenko1998/chinchillas-show/application:latest

      - name: Build and publish Nginx
        run: |
          docker build .nginx --tag ghcr.io/alexbidenko1998/chinchillas-show/nginx:latest
          docker push ghcr.io/alexbidenko1998/chinchillas-show/nginx:latest

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Deploy 🚀
        run: docker stack deploy --prune --with-registry-auth -c docker-compose.yml chinchillas-show-frontend
        env:
          DOCKER_HOST: ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
