name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build-application:
    name: Build Application
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            SITE_ENVIRONMENT=production
            NUXT_DADATA_TOKEN=${{ secrets.NUXT_DADATA_TOKEN }}
          push: true
          tags: ghcr.io/alexbidenko/chinchillas-show/application:latest

  build-nginx:
    name: Build Nginx
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .nginx
          push: true
          tags: ghcr.io/alexbidenko/chinchillas-show/nginx:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04

    needs: [build-application, build-nginx]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Deploy 🚀
        run: docker stack deploy --prune --with-registry-auth -c docker-compose.yml chinchillas-show-frontend
        env:
          DOCKER_HOST: ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
