on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Create SSH key
        run: |
          sudo apt-get install -y rsync sshpass
          mkdir -p ~/.ssh/
          echo "${{secrets.HOST}}" > ~/.ssh/known_hosts
          echo -e 'Host *\n\tStrictHostKeyChecking no\n\n' > ~/.ssh/config
      - name: Update Nginx
        run: |
          rsync -e 'sshpass -p ${{secrets.PASSWORD}} ssh' -avz --delete-after .nginx/chinchillas-show.conf ${{secrets.USER}}@${{secrets.HOST}}:/etc/nginx/conf.d/chinchillas-show.conf
          ssh ${{secrets.USER}}@${{secrets.HOST}} 'service nginx reload'
      - uses: alex-ac/github-action-ssh-docker-compose@master
        name: Docker-Compose Remote Deployment
        with:
          ssh_host: ${{secrets.HOST}}
          ssh_private_key: ${{ secrets.SSH_KEY }}
          ssh_user: ${{ secrets.USER }}
