on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          ref: master
      - name: Create SSH key
        run: |
          sudo apt-get install -y rsync sshpass
          mkdir -p ~/.ssh/
          echo "37.140.192.11" > ~/.ssh/known_hosts
          echo -e 'Host *\n\tStrictHostKeyChecking no\n\n' > ~/.ssh/config
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Packages
        run: npm i
      - name: Build artifacts
        run: |
          npm run build
          npm run export
      - name: Deploy
        run: rsync -e 'sshpass -p Q!3Hb4c3 ssh' -avzP dist u0690120@37.140.192.11:/var/www/u0690120/data/www/chinchillas-show.com
        shell: bash
