on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.HOST}}" > ~/.ssh/known_hosts
          echo -e 'Host *\n\tStrictHostKeyChecking no\n\n' > ~/.ssh/config
      - name: Deploy
        run: DOCKER_HOST="ssh://${{secrets.USER}}@${{secrets.HOST}}" docker-compose up -d
        shell: bash
